import base64
import time
from datetime import datetime

import markdown2
import pdfkit
import requests
import streamlit as st


def call_api(method, url, headers, params=None):
    response = requests.request(method=method, url=url, params=params, headers=headers)
    return response.json()


def parse_datetime(date_str):
    try:
        return datetime.strptime(date_str, "%Y-%m-%d %H:%M:%S")
    except (ValueError, TypeError):
        return None


def markdown_to_pdf(profile_with_markdown, markdown_content):
    profile_content = markdown2.markdown(profile_with_markdown)
    html_content = markdown2.markdown(markdown_content, extras=["fenced-code-blocks", "tables", "footnotes"])

    with open("logo.svg", "rb") as image_file:
        encoded_svg = base64.b64encode(image_file.read()).decode("utf-8")

    # Embed in HTML as image
    svg_img_html = f'<img src="data:image/svg+xml;base64,{encoded_svg}" class="svg-icon" alt="Logo">'

    # Create the main HTML content first
    main_html = f"""
        <div>
            {svg_img_html}
            <div class="profile-info">
                {profile_content}
            </div>
            <div class="main-content">
            {html_content}
            </div>
        </div>
    """

    # Add footer with CSS to ensure it appears on the last page
    full_html = f"""
        <html>
        <head>
        <meta charset='utf-8'>
        <link href="https://fonts.googleapis.com/css2?family=Roboto&display=swap" rel="stylesheet">
        <style>
            @page {{
                margin: 0px;
                @bottom-center {{
                    content: element(footer);
                }}
            }}
            body {{
                font-family: "Open Sans", sans-serif;
                color: #666666;
                margin: 0;
                padding: 0;
            }}
            .profile-info {{
                color: #CCCCCC;  
                background-color: #1A1A1A;
                padding: 20px 40px;
                margin-top: 10px;
                border-bottom: 2px solid #28B566;
            }}
            .profile-info a {{
                color: #CCCCCC;
            }}
            .profile-info h1 {{
                font-size: 24px;
                font-weight: 600;
                line-height: 1.3;
                color: #28B566;
                margin-top: 0.2em;
                margin-bottom: 0.6em;
            }}
            .main-content {{
                padding: 0 40px 40px 40px;
            }}
            h2 {{
                font-size: 24px;
                font-weight: 500;
                line-height: 1.3;
                color: #0F783D;
                margin-top: 1.2em;
                margin-bottom: 0.6em;
            }}
            h3 {{
                font-size: 18px;
                font-weight: 400;
                line-height: 1;
                margin-top: 1em;
                margin-bottom: 0.3em;
            }}
            .svg-icon {{
                display: block;
                width: 300px;
                height: auto;
            }}
            #footer {{
                position: running(footer);
                text-align: center;
                color: grey;
                font-family: Arial, sans-serif;
                font-size: 14px;
            }}
            .pagenumber:before {{
                content: counter(page);
            }}
            .pagecount:before {{
                content: counter(pages);
            }}
        </style>
        </head>
        <body>
            {main_html}
            <div id="footer">
                <p>This is an automated report generated by Panopto AI SDR.</p>
            </div>
        </body>
        </html>
        """

    pdf_options = {
        "page-size": "A4",
        "encoding": "UTF-8",
        "enable-local-file-access": "",
        "margin-top": "5mm",
        "margin-right": "0mm",
        "margin-left": "0mm",
        "margin-bottom": "20mm",
        "footer-html": "footer.html"
    }

    # First create a footer HTML file
    with open("footer.html", "w", encoding="utf-8") as f:
        f.write("""
        <html>
        <head>
            <style>
                .footer {
                    text-align: center;
                    color: grey;
                    font-family: Arial, sans-serif;
                    font-size: 14px;
                    margin-top: 1.2em;
                }
            </style>
        </head>
        <body>
            <div class="footer">This is an automated report generated by Panopto AI SDR.</div>
        </body>
        </html>
        """)

    pdf = pdfkit.from_string(full_html, output_path=None, options=pdf_options)

    # Clean up the temporary footer file
    import os
    os.remove("footer.html")

    return pdf
